[package]
name = "nerve-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "nv"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
libc.workspace = true
nerve-adapter = { path = "../nerve-adapter" }
nerve-config = { path = "../nerve-config" }
nerve-core = { path = "../nerve-core" }
nerve-types = { path = "../nerve-types" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
