[package]
name = "nerve-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
nerve-adapter = { path = "../nerve-adapter" }
nerve-config = { path = "../nerve-config" }
nerve-patch = { path = "../nerve-patch" }
nerve-types = { path = "../nerve-types" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true
