[package]
name = "nerve-types"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
nerve-patch = { path = "../nerve-patch" }
serde.workspace = true
serde_json.workspace = true
ulid.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
